{% set data = load_setup_py_data() %}

package:
  name: "mhp"
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - pandas
    - scipy
    - matplotlib-base
    - rdkit

build:
  script: python3 setup.py install
  noarch: python
  number: 1
  entry_points:
    - makePol = mhp.MakePolymer:main
    - customPol = mhp.custom_input_to_mol_file:main
    - mhpSettings = mhp.settings:main
    - mhpNB = mhp.nb:main
    - mhpLib = mhp.smiles:main

test:
  imports:
    - rdkit
    - scipy
    - mhp
  commands:
    - makePol -h
    - customPol -h
    - mhpSettings -h
    - mhpSettings -s
    - mhpLib -h
    - mhpLib -e
    - mhpLib -m

# requirements:
#   build:
#     - setuptools
#     - python
#     - pandas
#     - scipy
#     - matplotlib
#     - rdkit

#   host:
#     - python

# build:  
#   preserve_egg_dir: True
