{% set data = load_setup_py_data() %}

package:
  name: "mhp"
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python

  run:
    - pandas
    - python
    - scipy
    - matplotlib-base
    - rdkit

build:
  script: python3 setup.py install
  noarch: python
  number: 5
  entry_points:
    - makePol = mhp.MakePolymer:main
    - customPol = mhp.custom_input_to_mol_file:main

test:
  imports:
    - rdkit
    - scipy
    - mhp
  commands:
    - makePol -h
    - customPol -h


