{% set data = load_setup_py_data() %}

package:
  name: "mhp"
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python

  run:
    - pandas
    - python
    - scipy
    - matplotlib-base

build:
  script: python3 setup.py install
  noarch: python

test:
  imports:
    - rdkit
    - scipy
    - mhp